baseURL = 'https://orchidees-rouges.netlify.app/'
languageCode = 'fr'
title = '1 minute'
expandedTitle = '1 minute dans le monde'

[menu]
  [[menu.main]]
    name = "À propos"
    url = "/a-propos/"
    weight = 1
  [[menu.main]]
    name = "Les Histoires"
    url = "/histoires/"
    weight = 2
  [[menu.main]]
    name = "Mentions légales"
    url = "/mentions-legales/"
    weight = 3
  [[menu.resources]]
    name = "Génération égalité"
    url = "url"
    weight = 1
  [[menu.resources]]
    name = "ONU Femmes France"
    url = "url"
    weight = 2
  [[menu.resources]]
    name = "ECOSOC"
    url = "url"
    weight = 3
  [[menu.legal]]
    name = "Mentions légales"
    url = "/mentions-legales"
    weight = 1
  [[menu.legal]]
    name = "Plan du site"
    url = "/plan-du-site"
    weight = 2
  [[menu.legal]]
    name = "À propos"
    url = "/a-propos"
    weight = 3